title: 回去等通知吧
description: 小陈在职场夹缝里，拆解领导的灵魂拷问和公司开发 Agent 时的麻烦事。
author: 小陈
url: https://QHChen96.github.io
baseurl: ""
lang: zh-CN
timezone: Asia/Shanghai
permalink: /posts/:year/:month/:day/:title/
markdown: kramdown
kramdown:
  input: GFM
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
